Fs = 1000;
t = 0:1/Fs:1-1/Fs;
fc = 100;
fm = 5;
kf = 50;
m_nader = sin(2*pi*fm*t);
c_nader = cos(2*pi*fc*t);
y_nader = cos(2*pi*fc*t + kf*cumsum(m_nader)/Fs);
figure('Position', [100, 100, 1200, 800]);
subplot(5,1,1);
plot(t, m_nader);
title('Modulating Signal');
xlabel('Time (s)');
ylabel('Amplitude');
subplot(5,1,2);
plot(t, c_nader);
title('Carrier Signal');
xlabel('Time (s)');
ylabel('Amplitude');
subplot(5,1,3);
f_nader = -Fs/2:Fs/length(m_nader):Fs/2-Fs/length(m_nader);
plot(f_nader, abs(fftshift(fft(m_nader))));
title('Frequency Spectrum of Modulating Signal');
xlabel('Frequency (Hz)');
ylabel('Magnitude');
xlim([-30, 30]);
subplot(5,1,4);
carrier_spectrum = abs(fftshift(fft(c_nader)));
f_carrier = linspace(-Fs/2, Fs/2, length(carrier_spectrum));
plot(f_carrier, carrier_spectrum);
title('Frequency Spectrum of Carrier Signal');
xlabel('Frequency (Hz)');
ylabel('Magnitude');
xlim([-110, 110]); 
subplot(5,1,5);
plot(f_nader, abs(fftshift(fft(y_nader))));
title('Frequency Spectrum of Modulated Signal');
xlabel('Frequency (Hz)');
ylabel('Magnitude');
xlim([-200, 200]);